# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Uday Yalamanchili
title: Software Engineer
email: yalamanchiliudaysankar@gmail.com
website: https://udayyalamanchili.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: UdayYalamanchili
linkedin_username: uday-y

# Google Analytics and Tag Manager
gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  Software Engineer with over 3 years of experience developing data-driven applications and deploying ML models. 
  I specialize in building scalable data pipelines and backend systems while leveraging advanced machine learning techniques to deliver impactful results. 
  My technical expertise includes Python, Java, and popular frameworks like TensorFlow and PyTorch, with hands-on experience in both cloud environments and containerization. 
  Currently, I work as a Senior Software Engineer at Microchip Technology, focusing on building software, ML-based tools and improving device integration.

  I am most skilled in: <mark>Machine Learning</mark>, <mark>Data Engineering</mark>, and <mark>Backend Development</mark>

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Mobile Offloading Android Application
        link: https://github.com/UdayYalamanchili/Photog
        additional_links:
          - title: Image Classification - Android
            icon: fab fa-github
            url: https://github.com/UdayYalamanchili/Photog
        description: |
          - Developed an Android application with Flask servers for image capture and classification of handwritten digits using a CNN model, achieving 97% accuracy.
          - Implemented an image processing pipeline for filtering, thresholding, and contour detection, optimizing computational load through mobile offloading.

      - layout: top-middle
        title: Neural Image Caption Generator
        additional_links:
          - title: Neural Image Caption Generator
            icon: fab fa-github
            url: https://github.com/UdayYalamanchili/Image-Caption-Generator
        description: |
          - Built an image captioning model utilizing an Attention mechanism to generate rich, descriptive captions for images.
          - Encoded inputs using VGG16 and implemented an LSTM architecture for the decoder, visualizing model focus during caption generation.

      - layout: top-middle
        title: Zero-Shot Common Sense Question Answering
        additional_links:
          - title: Zero-Shot QA Model
            icon: fab fa-github
            url: https://github.com/UdayYalamanchili/
        description: |
          - Developed a question answering model leveraging unsupervised learning techniques for zero-shot inference.
          - Used T5 model pre-trained on the Common-Gen dataset, employing a rules-based approach to create a synthetic dataset for training, achieving 65% accuracy on the Common Sense QA dataset.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: Microchip Technology
        link: http://microchip.com
        sub_title: Senior Software Engineer
        caption: July 2023 - Present
        description: |
          - Developed an anomaly detection model for log analysis using fastText and fine-tuned BERT for masked language modelling, reducing issue reporting time by 60%. Clustered and visualized anomalies using Matplotlib to match them with known issues, streamlining root cause identification.
          - Containerized MPLAB X IDE with Docker for seamless integration between microcontrollers and debuggers via a Java-based GUI, enhancing device interaction through a noVNC web interface.
          - Built a Java utility to enhance device search and connection across systems, simplifying the device interaction process.
          - Enhanced Jenkins CI pipelines by integrating automatic error flagging and categorization using the Jira API, optimizing workflow automation and improving testing efficiency.

      - layout: left
        title: Thorogood Associates
        link: https://www.thorogood.com
        sub_title: Software Engineer
        caption: July 2019 - July 2021
        description: |
          - Developed a carbon footprint prediction model for Unilever using XGBoost, improving forecast accuracy by 15% across 40 countries. Built scalable ETL pipelines in Apache Spark to process over 15TB of sustainability data, enabling real-time monitoring and delivering actionable insights through PowerBI.
          - Engineered data pipelines to enhance rewards distribution, cutting processing time by 70%. Utilized K-means clustering to classify partners into performance tiers for targeted rewards and migrated the system to Azure for greater scalability.
          - Built a time-sheet website for over 150 consultants using Typescript and Angular for the front-end. Built scalable RESTful APIs and micro-services with Django and SQL Server for efficient data management and seamless backend integration.
          - Resolved faulty data pipelines, implementing monitoring and logging mechanisms to track performance and manage irregular data loads during COVID-19, leading to a 20% increase in revenue team resolution rates.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Arizona State University
        caption: 2021 - 2023
        sub_title: Master of Science, Computer Science
        subcaption: GPA 3.92 / 4.0
        description: |
          - Courses: Machine Learning, Data Mining, Natural Language Processing, Artificial Intelligence, Digital Video Processing, Computer Vision

      - layout: left
        title: Birla Institute Of Technology & Science, Pilani
        caption: 2015 - 2019
        sub_title: Bachelor of Engineering (Hons.) in Electronics & Communication
        description: |
          - Courses: Data Structures and Algorithms, Object-Oriented Programming, Operating Systems

  - title: Skills
    layout: text
    content: |
      - **Programming Languages**: Python, Java, C, C++, JavaScript, SQL, MATLAB
      - **Tools**: AWS, Azure, Spark, FastAPI, Docker, Kubernetes, Jenkins, Django, Flask, MySQL, MongoDB, Git, MSBI, Android
      - **Machine Learning**: PyTorch, TensorFlow, Scikit-learn, Pandas, Regression, Time Series Analysis, Generative AI, Fine-tuning LLMs

  - title: Awards & Honors 
    layout: text
    content: |
      - **Thorogood Star Award** (Feb 2020, Oct 2020) - Awarded for the best performer across the company during the month.

  - title: Extra Curriculars
    layout: list
    content:  
      - layout: left
        title: Department of Publicity & Public Relations
        caption: March 2017 - March 2018
        sub_title: Head of Department
        description: |
          - Elected as head by the student body for the cultural festival “Pearl”, leading a team of ~90 students to achieve a 150% increase in footfall.

      - layout: left
        title: VFX Club
        caption: September 2016 - May 2017
        sub_title: Head of Video Composition
        description: |
          - Conducted regular classes on VFX and video editing, enhancing the skill set of the student community.

      - layout: left
        title: National Service Scheme     
        caption: August 2016 – August 2017
        sub_title: Volunteer
        description: |
          - Identified and resolved needs in local villages, actively participating in clean-up and tree plantation drives.

  - title: Languages
    layout: text
    content: |
      - English, Telugu, Hindi

  - title: A Little More About Me
    layout: text
    content: |
      - Alongside my interests in machine learning and software engineering, I enjoy:
      - Football
      - Gaming
      - Exploring new places!

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag