# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Uday Yalamanchili
title: Senior Network System Administrator
email: yalamanchiliudaysankar@gmail.com
website: https://udayyalamanchili.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: facespics
github_username:  UdayYalamanchili
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: sleety_basher
linkedin_username: uday-y
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Uday and I'm a graduate student studying computer science at Arizona State University. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Course Information Repository
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          1.	Created a repository that stores course information like id, credits, capacity, days, time by using <mark>hash table</mark>.
          2.	User can insert new courses, search and update info like capacity of the course. 
          3.  Used open addressing with double hashing to resolve collisions and came up with a custom hash function to reduce the collisions.
          
#    content:   
#      - layout: top-middle
#         title: Minitorch
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           1.  Ongoing project which is a python re-implementation of the Torch API. The final library can run Torch code.
#           2.  Implemented infrastructure like operators, higher order functions, module, Auto-differentiation, backpropagation for scalars.

#    content:   
#      - layout: top-middle
#         title: Sentiment Analysis
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           1.  Built a sentiment classifier on the Sentiment140 dataset using MLP classifier and BERT encodings for word representation.
#           2.  Implemented a model that achieved 82% testing accuracy.

#    content:   
#      - layout: top-middle
#         title: Portfolio Analysis
#         link: github.com/sproogen
#         # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
#           # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#           #   icon: fab fa-github
#           #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#         description: | # this will include new lines to allow paragraphs
#           1.  Automated the process of scraping data using Beautiful Soup library, calculated historical returns, correlation of the share of the stock w.r.t other stocks and analysed risk-return performance to create a well-diversified portfolio using Markowitz model along with tools and libraries in Python and Excel. 
#           2.  Successfully identified and picked stocks through market research, resulting in a well performing portfolio with returns of ~14%.

          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Thorogood Associates
        link: https://www.thorogood.com
        # link_text: boringcompany.com
        sub_title: Business Intelligence & Analytics Consultant
        caption: July 2019 - July 2021
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          1.  Delivered end-to-end BI solutions. Skilled in Data Modelling <mark>(ETL)</mark> using Microsoft BI suite (SQL, SSIS and Tabular), Data Visualization and Reporting using tools like Power BI.
          2.  Built models on financial data of a major FMCG firm across their product catalogue.
          3.  Collaborated with clients of a leading tobacco firm, developed ETL interfaces and debugged issues.
     
#     content:
#       - layout: left
#         title: JPMorgan Chase & Co.
#         link: https://www.jpmorganchase.com
#         # link_text: boringcompany.com
#         sub_title: Analyst
#         caption: July 2018 - December 2018
#         quote: >
#           Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#         description: | # this will include new lines to allow paragraphs
#           1.  Analysed and reported operational errors (System/Manual) in 14 locations across Asia-Pacific.
#           2.  Collaborated with Sales, Ops on the on-boarding of clients and implementation generating revenue in millions. 
#           3.  Analysed and reported the trends, key statistics on volume/value of Foreign Exchange transactions of 14 APAC countries. ~80% of manual FX transactions in China were automated with the help of these reports which reduced the FX related errors over a quarter by ~90%.
#           4.  Real time monitoring and subsequent escalation of transaction queue of Korea market to mitigate potential client impact. 



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Arizona State University
        caption: 2021 - 2023
        sub_title: MS Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Football
      - Gaming
      - Exploring new places!
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
